### ISSUE TITLE
Exception thrown when a database name is not provided

### ISSUE THREAD

**Issue by emtammaru** [tekmaven/NServiceBus.Persistence.MongoDb#9]
Database name is optional in MongoDB connection string documentation:

https://docs.mongodb.org/v3.0/reference/connection-string/

The offending code is here:

https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/blob/master/src/NServiceBus.Persistence.MongoDb/Database/MongoDbStorage.cs#L92

**Comment by tekmaven** [comment]
If the database name is optional, how will we get a value for `databaseName` on line 98? 

https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/blob/master/src/NServiceBus.Persistence.MongoDb/Database/MongoDbStorage.cs#L98

**Comment by emtammaru** [comment]
Create a database?  [NServiceBus.MongoDB](https://github.com/sbmako/NServiceBus.MongoDB) does not require a database name

**Comment by tekmaven** [comment]
This is by design, which is why we have an explicit exception for it.  

I am open to removing this restriction if we can generate a meaningful value for `databaseName`.  In NServiceBus v6, [EndpointName is required](https://docs.particular.net/nservicebus/upgrades/5to6/#update-endpoint-configuration), so we may be able to use that.
